# Generated by Django 4.2.7 on 2023-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Currency rate'),
        ),
    ]
